name: compiler auto test
run-name: ${{ github.actor }} is testing out compiler function ðŸš€
on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maxxing/compiler-dev
    defaults:
      run:
        working-directory: ./project
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: test koopa
        run: |
          autotest -koopa -s lv1 .
          autotest -koopa -s lv3 .
          autotest -koopa -s lv4 .
          autotest -koopa -s lv5 .
          autotest -koopa -s lv6 .
          autotest -koopa -s lv7 .
      - name: test riscv
        run: |
          autotest -riscv -s lv1 .
          autotest -riscv -s lv3 .
          autotest -riscv -s lv4 .
          autotest -riscv -s lv5 .
          autotest -riscv -s lv6 .
          autotest -riscv -s lv7 .
