name: compiler auto test
run-name: ${{ github.actor }} is testing out compiler function ðŸš€
on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maxxing/compiler-dev
    defaults:
      run:
        working-directory: ./project
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: test koopa
        run: autotest -w debug -koopa .
      - name: test riscv
        run: autotest -w debug -riscv .