name: compiler auto test
run-name: ${{ github.actor }} is testing out compiler function ðŸš€

on:
  push:
    paths:
      - 'project/**'
  pull_request:
  workflow_dispatch:

jobs:
  build_compiler:
    runs-on: ubuntu-latest
    container:
      image: maxxing/compiler-dev
    defaults:
      run:
        working-directory: ./project
    outputs:
      artifact_name: compiler-binary
    steps:
      - uses: actions/checkout@v5
      
      - name: Install Ninja
        run: |
          apt-get update && apt-get install -y ninja-build
          ninja --version
          
      - name: Build Binary
        run: make

  test_compiler:
    needs: build_compiler
    runs-on: ubuntu-latest
    container:
      image: maxxing/compiler-dev
    strategy:
      fail-fast: false
      matrix:
        test_type: [koopa, riscv]
    defaults:
      run:
        working-directory: ./project
    steps:
      - uses: actions/checkout@v5

      - name: Run Test
        run: autotest -w debug -${{ matrix.test_type }} .

      - name: Upload Test Logs
        if: failure()
        uses: actions/upload-artifact@v5
        with:
          name: test-logs-${{ matrix.test_type }}
          path: project/debug/