name: compiler auto test
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: maxxing/compiler-dev
    defaults:
      run:
        working-directory: ./project
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: pwd
      - name: build compiler
        run: make build
      - name: test koopa
        run: |
          autotest -koopa -s lv1 .
          autotest -koopa -s lv2 .
          autotest -koopa -s lv3 .
          autotest -koopa -s lv4 .
          autotest -koopa -s lv5 .
          autotest -koopa -s lv6 .
